"""Chat request and response schemas."""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class ChatMessageRequest(BaseModel):
    message: str = Field(..., min_length=1)


class ChatMessageResponse(BaseModel):
    id: int
    user_message: str
    bot_message: str
    sources: List[Dict[str, str]] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    created_at: datetime
    ui_hint: Optional[str] = None  # "resolution_prompt" | "escalate_prompt" | None

    class Config:
        from_attributes = True


class EscalateQuestionsResponse(BaseModel):
    """Questions generated by the LLM to enrich a support ticket."""
    intro: str
    questions: List[str]
    context_summary: str


class EscalateRequest(BaseModel):
    """Create a support ticket, optionally enriched with user answers."""
    question: str = Field(..., min_length=1)
    answers: Optional[List[str]] = None        # answers to escalation questions
    context_summary: Optional[str] = None      # LLM-generated problem summary


class EscalateResponse(BaseModel):
    ticket_id: int
    message: str = "Tu consulta ha sido escalada al equipo."
